// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonDb.Models;

namespace PokemonDb.Migrations
{
    [DbContext(typeof(PokemonDbContext))]
    [Migration("20210107232930_AddTrainer")]
    partial class AddTrainer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PokemonDb.Models.PokeType", b =>
                {
                    b.Property<int>("PokeTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PokeTypeName");

                    b.HasKey("PokeTypeId");

                    b.ToTable("PokeTypes");
                });

            modelBuilder.Entity("PokemonDb.Models.Pokedex", b =>
                {
                    b.Property<int>("PokedexId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PokeTypeId");

                    b.Property<int>("PokemonId");

                    b.HasKey("PokedexId");

                    b.HasIndex("PokeTypeId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Pokedex");
                });

            modelBuilder.Entity("PokemonDb.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PokemonDescription");

                    b.Property<string>("PokemonGender");

                    b.Property<int>("PokemonLevel");

                    b.Property<string>("PokemonName");

                    b.Property<int>("TrainerId");

                    b.HasKey("PokemonId");

                    b.HasIndex("TrainerId");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonDb.Models.Trainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("TrainerName");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("PokemonDb.Models.Pokedex", b =>
                {
                    b.HasOne("PokemonDb.Models.PokeType", "PokeType")
                        .WithMany("Pokemons")
                        .HasForeignKey("PokeTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PokemonDb.Models.Pokemon", "Pokemon")
                        .WithMany("PokeTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PokemonDb.Models.Pokemon", b =>
                {
                    b.HasOne("PokemonDb.Models.Trainer", "Trainer")
                        .WithMany("Pokemons")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
